version: '2'

services:
  app:
    build: .
    ports:
     - "3000:3000"    # Node web server
    working_dir: /app
    volumes:
     - ./:/app/
     - /app/node_modules
    entrypoint: ["npm",  "start", "-s"]
